version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: user-service
      POSTGRES_PASSWORD: password01
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always  